spring.application.name=routine-tracker

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
api.security.token.secret=${JWT_SECRET}
app.cors.allowed-origin=${FRONTEND_URL}

app.cookie.secure=true
app.cookie.same-site=None